### ISSUE TITLE
Error when running any of the functions

### ISSUE THREAD

**Issue by anuj2054** [RaphaelS1/survivalmodels#2]
Hi, 

I get below when I run any of the functions:

Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'pycox'

I made sure to install pycox using 

conda install -c powerai pycox

But the error message still shows up.
Even when I do 

reticulate::import("pycox") 

I still see the message.

**Comment by RaphaelS1** [comment]
Hi @anuj2054 I've just updated to readme, can you let me know if this solves the problem for you? 

See section 'Python models' https://github.com/RaphaelS1/survivalmodels/blob/master/README.md

**Comment by anuj2054** [comment]
After installing all the required python packages through reticulate and conda.
pytorch, pycox are both installed.

I get the following:

> survivalmodels::deepsurv(simsurvdata(50))
Error in py_module_import(module, convert = convert) : 
  NameError: name '_C' is not defined

**Comment by RaphaelS1** [comment]
Hm, sorry I don't know. This seems to be a Python/reticulate issue and not with this package.

See e.g. https://github.com/pytorch/pytorch/issues/1633
