### ISSUE TITLE
bug in get_pycox_activation

### ISSUE THREAD

**Issue by sebffischer** [RaphaelS1/survivalmodels#29]
See: https://github.com/mlr-org/mlr3extralearners/issues/182

The bug is in `get_pycox_activation`

The lines 316 - 321 all construct the activation function even when `construct = FALSE`

**Comment by sebffischer** [comment]
Also I think that it is quite unexpected that the parameter values for an activaton function are not used when construct = FALSE, this should at least throw a message or something

**Comment by RaphaelS1** [comment]
closed in #33
