### ISSUE TITLE
Most Basic Usage Example Not Found

### ISSUE THREAD

**Issue by DarioS** [RaphaelS1/survivalmodels#30]
I would like to see a short example of the format

```r
fittedModel <- someFunction(trainData)
predictFunction(fittedModel, testData)
```

in Readme.md. How may I use these survival modelling functions independently of mlr3proba with a syntax similar to [e1071](https://cran.r-project.org/web/packages/e1071/index.html)?

**Comment by RaphaelS1** [comment]
https://github.com/RaphaelS1/survivalmodels/blob/main/README.md
