### ISSUE TITLE
Small doc update in akritas learner

### ISSUE THREAD

**Issue by bblodfon** [RaphaelS1/survivalmodels#35]
In [predict.akritas](https://github.com/RaphaelS1/survivalmodels/blob/main/R/akritas.R#L85), `risk` is not the negative mean of the survival time, but the sum of the cumulative hazard using the `surv_to_risk` [function](https://github.com/RaphaelS1/survivalmodels/blob/main/R/akritas.R#L175).

**Comment by RaphaelS1** [comment]
Good spot! Want to create a PR? ;)

**Comment by bblodfon** [comment]
#36

**Comment by RaphaelS1** [comment]
Closed in https://github.com/RaphaelS1/survivalmodels/pull/36
