### ISSUE TITLE
Stark model result differences in a simple comparison

### ISSUE THREAD

**Issue by Jesse-Islam** [RaphaelS1/survivalmodels#5]
I was testing out deephit and deepsurv, and expect the result from a simple dataset to be relatively similar. However, this does not appear to be the case. I've appended a minimal reproducible example, where the survival estimates are not similar at all for this single individual. My expectations are not met, however I'm relatively new at using these methods. Do these results seem reasonable, or is there a potential implementation issue?

``` r
library(survivalmodels)
# common parameters

#prepData
data<-simsurvdata(n=1000)
samp<-sample(seq(1,nrow(data),by=1), nrow(data)-1)
train<-data[samp,]
test<-data[-samp,-c(ncol(data))]

#deephit model

fhtnn<-deephit(data = train, frac = 0, activation = "relu",
               num_nodes = c(20L,10L,10L,5L,5L,1L), dropout = 0.5, early_stopping = TRUE, epochs = 10000L,
               batch_size = 32L,device = "cpu",best_weights=T)

hitnnsurv<- predict(fhtnn,newdata = test,type="survival")
hitnnsurv<-t(rbind(as.numeric(colnames(hitnnsurv)),as.numeric(hitnnsurv[1,])))
plot(hitnnsurv[,1],(hitnnsurv[,2]),type='s')
```

![](https://i.imgur.com/mT330ka.png)

``` r



#deepsurv model
coxnn<-deepsurv(data = train, frac = 0, activation = "relu",
                num_nodes = c(20L,10L,10L,5L,5L,1L), dropout = 0.5, early_stopping = TRUE, epochs = 1000L,
                batch_size = 32L,device = "cpu",best_weights=T)

coxnnsurv<- predict(coxnn,newdata = test,type="survival")
coxnnsurv<-t(rbind(as.numeric(colnames(coxnnsurv)),as.numeric(coxnnsurv[1,])))
plot(coxnnsurv[,1],coxnnsurv[,2],type='s')
```

![](https://i.imgur.com/bv0oLMf.png)

``` r

sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 18.04.5 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
#> LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] survivalmodels_0.1.6
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.6        lattice_0.20-41   digest_0.6.27     rappdirs_0.3.2   
#>  [5] grid_4.0.3        jsonlite_1.7.2    magrittr_2.0.1    evaluate_0.14    
#>  [9] highr_0.8         rlang_0.4.10      stringi_1.5.3     Matrix_1.3-2     
#> [13] reticulate_1.18   rmarkdown_2.7     tools_4.0.3       stringr_1.4.0    
#> [17] xfun_0.21         yaml_2.2.1        compiler_4.0.3    htmltools_0.5.1.1
#> [21] knitr_1.31
```

<sup>Created on 2021-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by RaphaelS1** [comment]
Hi @Jesse-Islam , thanks for using survivalmodels! Interesting question!

Here are my thoughts:

1. I don't think these should be expected to behave the same in general: DeepSurv is a deep Cox PH model (https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-018-0482-1) whereas DeepHit is specifically a non-PH model for competing risks (http://medianetlab.ee.ucla.edu/papers/AAAI_2018_DeepHit).
2. Your testing method doesn't provide a 'fair' comparison as models should be compared by average performance and not on a single testing point, if you instead compare the models with the `cindex` then you'll see these perform very similarly (see below)
3. When comparing models to see if they give similar results, always make sure to set a seed otherwise things could be different just by chance

See my experiment results below, just two things to point out here: i) there was a problem in my latest CRAN upload to the functions that have `:::` will be exported properly in my next release (tomorrow); ii) I will make a plotting function to make plotting easier; iii) clearly the plotting example could be better!

``` r
library(survivalmodels)
library(survival)

#prepData
data<-simsurvdata(n=1000)
samp<- sample(nrow(data), nrow(data) * 2/3)
train<-data[samp,]
test<-data[-samp,]

#deephit model
survivalmodels:::set_seed(1)
fhtnn<-deephit(data = train, epochs = 300)
hitnnsurv <- predict(fhtnn,newdata = test, type = "all")

#deepsurv model
survivalmodels:::set_seed(1)
coxnn<-deepsurv(data = train, epochs = 300)
coxnnsurv<- predict(coxnn,newdata = test, type="all")

# cindex
x = cbind(survivalmodels:::cindex(hitnnsurv$risk, test$time),
          survivalmodels:::cindex(coxnnsurv$risk, test$time))
names(x) <- c("DeepHit", "DeepSurv")
x
#>          [,1]      [,2]
#> [1,] 0.878812 0.8860534
#> attr(,"names")
#> [1] "DeepHit"  "DeepSurv"

# plot
plot(as.numeric(names(coxnnsurv$surv[190, ])),
     as.numeric(coxnnsurv$surv[190, ]), type = "s")
lines(as.numeric(names(hitnnsurv$surv[190, ])),
      as.numeric(hitnnsurv$surv[190, ]), type = "s", col = 2)
```

![](https://i.imgur.com/biDjXQn.png)

<sup>Created on 2021-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Jesse-Islam** [comment]
Good point, definitely not fair on my part. I do however believe that the inverse gaussian Deephit is approximating is relatively flexible, and they make a point to state that their method works for any number of events (including 1). 

1) I look forward to the update!
2) I'd argue your approach is great for when I'd like to custom ggplot, I was just lazy sorry about that.
3) haha unfortunate! I see see what you mean though, they can get relatively close.

A small note, I was sifting through the source code and couldn't find a way to supply my own survival times to either function. Both DeepSurv and DeepHit are looking at the same data, so I'd expect a similar number of steps... but that does not appear to be the case. Is there a reason for this? As this is only somewhat related to the original issue I'll be happy to move this discussion elsewhere. Thanks for wrapping pycox R!

**Comment by thialam** [comment]
Thank you for directing me to this thread, Raphael - super helpful!

But this also led to several more questions - hope you don't mind!

1. While implementing cindex, for some reason it keeps giving me the following error:
```
> breast_deepsurvpreds <- predict(breast_deepsurv, newdata = testing.naomit, type="survival")
> cindex(breast_deepsurvpreds, testing.naomit$time)
Error in if (!(formula.names[1] == "~") || (match("$", formula.names,  : 
  missing value where TRUE/FALSE needed
```
I tried looking at the documentation but I'm not sure what exactly I was missing. I also checked and made sure neither side contains NA. Any insight?

2. I understood that concordance is time-dependent - how do we calculate time-dependent concordance on deepsurv generated predictions? Here's how I was calculating concordance without using `cindex`:
```
rcorr.cens(breast_deepsurvpreds[,200], Btestsurv) #concordance at the 200th time point (not 200D, but correspondingly, around 350D)
       C Index            Dxy           S.D.              n        missing     uncensored 
  6.590432e-01   3.180865e-01   4.670553e-02   3.430000e+02   0.000000e+00   1.400000e+02 
Relevant Pairs     Concordant      Uncertain 
  6.292000e+04   4.146700e+04   5.437000e+04 
```
I specified concordance at the 200th column - it's not 200D, but the 200th column - of the results that I posted [here](https://github.com/RaphaelS1/survivalmodels/issues/6) I actually want to calculate the concordance at e.g. 1000D across all models - Does the code I posted above, and what I'm asking make sense? (or am I hallucinating and confusing all my biostats - either way, I'm grateful for any insight!!)

Really appreciate your help :)

**Comment by RaphaelS1** [comment]
Sorry to be a pain but can you please copy/paste your questions into a new issue as it is unrelated to this one? Then happy to discuss there

**Comment by RaphaelS1** [comment]
At the same time please produce a reprex with reprex::reprex so I can diagnose the problem more easily

**Comment by thialam** [comment]
Oh yes for sure! Thank you:)
