### ISSUE TITLE
Standardization of predictors

### ISSUE THREAD

**Issue by CYGUBICKO** [RaphaelS1/survivalmodels#7]
Does `survivalmodels` perform internal standardization of the predictors like scaling? Or do we have to do this before model fitting?

**Comment by RaphaelS1** [comment]
You have to do this yourself for all models. I recommend utilising [mlr3proba](https://github.com/mlr-org/mlr3proba) and associated packages as this will help streamline pre-processing (and any other tuning you may want to do). I might add a tutorial for this to make it clearer if you think that would be helpful/of interest

**Comment by CYGUBICKO** [comment]
Thanks for the feedback. This helps.
